# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 841196b23e3834628c14e7cf1901df7c237485ada44b91f283765537d7c2798cc0bf80d5ba391706439763040618c7cf701a4af38d0ae39c7b1d7876cac847fa

test:
  secret_key_base: 7b69d102f8fba2e7455ae6ce53b22bf6a0646878035092efe9c363cc7d6606e3bb82b7f3ba8347bac4efc5f327880effa274e33c65626ee293e40cba476a8874

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
